<?php
/**
 * Theme functions and definitions.
 * This child theme was generated by Merlin WP.
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 */

/*
 * If your child theme has more than one .css file (eg. ie.css, style.css, main.css) then
 * you will have to make sure to maintain all of the parent theme dependencies.
 *
 * Make sure you're using the correct handle for loading the parent theme's styles.
 * Failure to use the proper tag will result in a CSS file needlessly being loaded twice.
 * This will usually not affect the site appearance, but it's inefficient and extends your page's loading time.
 *
 * @link https://codex.wordpress.org/Child_Themes
 */
function groci_child_enqueue_styles() {
	wp_enqueue_style('parent-style', get_template_directory_uri() . '/style.css');
	wp_enqueue_style('groci-child-style',
		get_stylesheet_directory_uri() . '/style.css',
		array('groci-style'),
		wp_get_theme()->get('Version')
	);
}

add_action('wp_enqueue_scripts', 'groci_child_enqueue_styles', 99);
/**
 * @package     WordPress
 * @subpackage  GlobeABC
 * @version     1.1.2
 *
 * Child Theme Functions File
 * Created by Ervin Pepic
 *
 */
function language_school_child_enqueue_styles() {
	wp_enqueue_style('language-school-child-style', get_stylesheet_uri(), array('theme-style'), '1.0.0', 'screen, print');
}

add_action('wp_enqueue_scripts', 'language_school_child_enqueue_styles', 11);

function custom_login_stylesheet() {
	wp_enqueue_style('custom-login', get_stylesheet_directory_uri() . '/login/login-styles.css');
}
add_action('login_enqueue_scripts', 'custom_login_stylesheet');
//* code goes here

add_action('wp_enqueue_scripts', 'enqueue_parent_styles');

function enqueue_parent_styles() {
	wp_enqueue_style('parent-style', get_template_directory_uri() . '/style.css');
}

function wpb_login_logo_url() {
	return home_url();
}
add_filter('login_headerurl', 'wpb_login_logo_url');

function wpb_login_logo_url_title() {
	return 'GlobeABC';
}
add_filter('login_headertext', 'wpb_login_logo_url_title');

function remove_logo_wp_admin() {
	global $wp_admin_bar;
	$wp_admin_bar->remove_menu('wp-logo');
}
add_action('wp_before_admin_bar_render', 'remove_logo_wp_admin', 0);

function custom_login_title($origtitle) {
	return 'Login Page | ' . get_bloginfo('name');

}
add_filter('login_title', 'custom_login_title', 99);

function custom_admin_title($admin_title, $title) {
	return 'Admin Panel | ' . get_bloginfo('name');
}
add_filter('admin_title', 'custom_admin_title', 10, 2);

function custom_footer_copyright() {
	echo '<span id="footer-thankyou">Developed by Ervin pepic </span>';
}

add_filter('admin_footer_text', 'custom_footer_copyright');
?>




